### PR TITLE
Update to use superagent

### PR DESCRIPTION
**Pull request by edpaget**
Also remove the need to build the project before requiring it

### CODE REVIEW

**Comment by edpaget** [comment]
This looks fine running with the Front-End to me. I can start adding tests to the project if we want to make sure I didn't break anything.

**Comment by chrissnyder** [comment]
Is this good to merge? Also seemed to run fine to me.

**Comment by edpaget** [comment]
Yeah I think this is good to go along with the PFE pull request, but brian is in transit today.

**Comment by chrissnyder** [comment]
OK, I think this is solid now. Unless someone brings up a reason not to, I'm going to merge this in this afternoon, then bump the version.

**Comment by edpaget** [comment]
@chrissnyder Can you bump the major version, so it doesn't get automatically picked up by the front-end deploy?

**Comment by chrissnyder** [comment]
Yep

**Pull request merged**
